export const PLAN_LIMITS = {
  free: {
    maxVacancies: 3,
    maxCandidatesPerMonth: 20,
    aiAnalysis: true,
    emailInbox: false,
    atsIntegrations: false,
    analytics: false,
    interviewQuestions: false,
    hiringReport: false,
    candidateRanking: false,
    csvImport: false,
    export: false,
  },
  pro: {
    maxVacancies: Infinity,
    maxCandidatesPerMonth: Infinity,
    aiAnalysis: true,
    emailInbox: true,
    atsIntegrations: true,
    analytics: true,
    interviewQuestions: true,
    hiringReport: true,
    candidateRanking: true,
    csvImport: true,
    export: true,
  },
  demo: {
    maxVacancies: 3,
    maxCandidatesPerMonth: 20,
    aiAnalysis: true,
    emailInbox: false,
    atsIntegrations: false,
    analytics: false,
    interviewQuestions: false,
    hiringReport: false,
    candidateRanking: false,
    csvImport: false,
    export: false,
  },
  demo_pro: {
    maxVacancies: 8,
    maxCandidatesPerMonth: 50,
    aiAnalysis: true,
    emailInbox: true,
    atsIntegrations: true,
    analytics: true,
    interviewQuestions: true,
    hiringReport: true,
    candidateRanking: true,
    csvImport: true,
    export: true,
  },
}

export function getPlanLimits(subscription: string) {
  return PLAN_LIMITS[subscription as keyof typeof PLAN_LIMITS] || PLAN_LIMITS.free
}
