import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import prisma from '@/lib/prisma'
import nodemailer from 'nodemailer'

function toCSV(candidates: any[]): string {
  const headers = ['Name', 'Email', 'Phone', 'Match Score', 'Status', 'Recommendation', 'Skills', 'Experience', 'Education', 'Summary', 'Vacancy', 'Source', 'Date Added']
  const rows = candidates.map(c => {
    const skills = (() => { try { return JSON.parse(c.skills || '[]').join('; ') } catch { return '' } })()
    return [
      `${c.firstName} ${c.lastName}`,
      c.email || '',
      c.phone || '',
      c.matchScore != null ? `${Math.round(c.matchScore)}%` : '',
      c.status,
      c.recommendation || '',
      skills,
      (c.experience || '').replace(/\n/g, ' '),
      (c.education || '').replace(/\n/g, ' '),
      (c.summary || '').replace(/\n/g, ' '),
      c.vacancy?.title || '',
      c.source,
      new Date(c.createdAt).toLocaleDateString(),
    ].map(v => `"${String(v).replace(/"/g, '""')}"`).join(',')
  })
  return [headers.join(','), ...rows].join('\n')
}

export async function GET(req: Request) {
  const session = await getServerSession(authOptions)
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const vacancyId = searchParams.get('vacancyId')
  const sendTo = searchParams.get('email')
  const userId = (session.user as any).id
  const isAdmin = (session.user as any).role === 'admin'

  const where: any = isAdmin ? {} : { userId }
  if (vacancyId) where.vacancyId = vacancyId

  let candidates: any[]
  try {
    candidates = await prisma.candidate.findMany({
      where,
      include: { vacancy: { select: { title: true } } },
      orderBy: [{ matchScore: 'desc' }, { createdAt: 'desc' }],
    })
  } catch {
    return NextResponse.json({ error: 'Failed to load candidates' }, { status: 500 })
  }

  const csv = toCSV(candidates)
  const filename = `candidates-${vacancyId || 'all'}-${new Date().toISOString().slice(0, 10)}.csv`

  if (sendTo) {
    const smtpHost = process.env.SMTP_HOST
    const smtpUser = process.env.SMTP_USER
    const smtpPass = process.env.SMTP_PASS
    if (!smtpHost || !smtpUser || !smtpPass) {
      return NextResponse.json({ error: 'Email not configured. Download the file instead.' }, { status: 400 })
    }
    try {
      const transporter = nodemailer.createTransport({
        host: smtpHost,
        port: parseInt(process.env.SMTP_PORT || '587'),
        secure: process.env.SMTP_SECURE === 'true',
        auth: { user: smtpUser, pass: smtpPass },
      })
      await transporter.sendMail({
        from: `CVMatch AI <${smtpUser}>`,
        to: sendTo,
        subject: `Candidate Export — ${candidates.length} candidates`,
        text: `Please find attached the candidate export with ${candidates.length} candidates.\n\nGenerated by CVMatch AI on ${new Date().toLocaleDateString()}.`,
        attachments: [{ filename, content: csv, contentType: 'text/csv' }],
      })
      return NextResponse.json({ success: true, count: candidates.length })
    } catch (err: any) {
      return NextResponse.json({ error: `Failed to send email: ${err.message}` }, { status: 500 })
    }
  }

  return new NextResponse(csv, {
    headers: {
      'Content-Type': 'text/csv',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  })
}
